name: CFMOTO U6
version: "1.0.1"
slug: cfmoto_u6
description: CFMOTO U6 EV telemetry via MQTT
url: https://github.com/marquis-de-muesli/cfmoto-u6-addon

arch:
  - amd64
  - aarch64

init: false

options:
  cfmoto_email: ""
  cfmoto_password: ""
  vehicle_id: ""

  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

  poll_interval: 60

schema:
  cfmoto_email: email
  cfmoto_password: password
  vehicle_id: str

  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password

  poll_interval: int